"use client";
import {type ChangeEvent,useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "../../lib/supabase/client";

type Data={company_name:string;registration_no:string;cidb_no:string;cidb_grade_status:string;blacklist_note:string;address:string;state:string;phone_no:string;fax_no:string;email:string;pic_name:string;main_director:string;main_shareholder:string;main_equity:string;main_share_percent:string;nominee_name:string;profiling_status:string;profiling_issue:string;source:string};
type Preview={row:number;data:Data};
type Staging=Preview&{id:string;companyId:string|null;match:string;status:string;next:string};
type Company={id:string;company_name:string|null;registration_no:string|null};
type Mapping=Record<keyof Data|"raw_row_number",string|null>;
type IntakeResult={inserted:number;matched:number;held:number;skipped:number;failed:number};
type ApproveResult={approved:number;updated:number;held:number;failed:number};

const fields:Array<keyof Data>=["company_name","registration_no","cidb_no","cidb_grade_status","blacklist_note","address","state","phone_no","fax_no","email","pic_name","main_director","main_shareholder","main_equity","main_share_percent","nominee_name","profiling_status","profiling_issue","source"];
const selectFields=["id","company_id",...fields,"raw_row_number","match_status","staging_status","next_action"].join(",");

function parseCsv(text:string){const out:string[][]=[];let row:string[]=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){cell+='"';i++;}else if(c==='"')quote=!quote;else if(c===","&&!quote){row.push(cell.trim());cell="";}else if((c==="\n"||c==="\r")&&!quote){if(c==="\r"&&n==="\n")i++;row.push(cell.trim());if(row.some(Boolean))out.push(row);row=[];cell="";}else cell+=c;}row.push(cell.trim());if(row.some(Boolean))out.push(row);return out;}
const nh=(v:string)=>v.toLowerCase().replace(/[^a-z0-9%]+/g,"");
function mapHeaders(headers:string[]):Mapping{const find=(...terms:string[])=>headers.find(h=>terms.some(t=>nh(h)===t||nh(h).includes(t)))||null;return{company_name:find("namasyarikat","companyname"),registration_no:find("nossm","ssmno","registrationno"),cidb_no:find("nocidb","cidbno"),cidb_grade_status:find("gredstatuscidb","gredcidb"),blacklist_note:find("catatanblacklistrisiko","blacklist","risiko"),address:find("alamat","address"),state:find("negeri","state"),phone_no:find("notelefon","telefon","phoneno"),fax_no:find("nofax","faxno"),email:find("email"),pic_name:find("pic","picname"),main_director:find("pengarahutama","maindirector"),main_shareholder:find("pemegangsahamutama","mainshareholder"),main_equity:find("ekuitiutama","mainequity"),main_share_percent:find("share%utama","mainsharepercent"),nominee_name:find("penama","nominee"),profiling_status:find("statusprofiling","profilingstatus"),profiling_issue:find("isuprofiling","profilingissue"),source:find("source","sumber"),raw_row_number:find("rawrow","rownumber")};}
function cell(h:string[],r:string[],key:string|null){const i=key?h.indexOf(key):-1;return i<0?"":r[i]?.trim()||"";}
function previewRows(headers:string[],rows:string[][],mapping:Mapping,file:string){return rows.map((values,index)=>{const data={} as Data;for(const field of fields)data[field]=cell(headers,values,mapping[field]);if(!data.source)data.source=file;const raw=Number.parseInt(cell(headers,values,mapping.raw_row_number),10);return{row:Number.isFinite(raw)?raw:index+2,data};});}
const normName=(v:string|null|undefined)=>(v||"").trim().toUpperCase().replace(/[.,]/g,"").replace(/\s+/g," ");
const normReg=(v:string|null|undefined)=>(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
function num(v:string){const n=Number(v.replace(/[%\s,]/g,""));return v.trim()&&Number.isFinite(n)?n:null;}
function db(data:Data){return{...data,company_name:data.company_name||null,registration_no:data.registration_no||null,cidb_no:data.cidb_no||null,cidb_grade_status:data.cidb_grade_status||null,blacklist_note:data.blacklist_note||null,address:data.address||null,state:data.state||null,phone_no:data.phone_no||null,fax_no:data.fax_no||null,email:data.email||null,pic_name:data.pic_name||null,main_director:data.main_director||null,main_shareholder:data.main_shareholder||null,main_equity:num(data.main_equity),main_share_percent:num(data.main_share_percent),nominee_name:data.nominee_name||null,profiling_status:data.profiling_status||null,profiling_issue:data.profiling_issue||null,source:data.source||"CSV Profiling"};}
function mapStage(row:Record<string,unknown>):Staging{const data={} as Data;for(const field of fields)data[field]=String(row[field]??"");return{id:String(row.id),companyId:row.company_id?String(row.company_id):null,row:Number(row.raw_row_number||0),data,match:String(row.match_status||"Company Not Found"),status:String(row.staging_status||"Review Hold"),next:String(row.next_action||"-")};}
function bm(v:string){return({"Matched":"Dipadankan","Company Not Found":"Syarikat Tidak Dijumpai","Ready for Review":"Sedia Disemak","Review Hold":"Tahan Semakan","Approved":"Diluluskan","Updated Existing Profile":"Profil Dikemas Kini","Imported to Company Profile":"Diimport ke Profil Syarikat"} as Record<string,string>)[v]||v;}

export default function StageProfilingPage(){
 const[supabase]=useState(()=>{try{return createClient();}catch{return null;}});
 const[file,setFile]=useState("");const[headers,setHeaders]=useState<string[]>([]);const[mapping,setMapping]=useState<Mapping>(()=>mapHeaders([]));const[preview,setPreview]=useState<Preview[]>([]);const[selectedPreview,setSelectedPreview]=useState<Preview|null>(null);
 const[staging,setStaging]=useState<Staging[]>([]);const[selectedStage,setSelectedStage]=useState<Staging|null>(null);const[connection,setConnection]=useState("Memuatkan Semakan Profil...");const[intakeMessage,setIntakeMessage]=useState("");const[approveMessage,setApproveMessage]=useState("");const[intakeResult,setIntakeResult]=useState<IntakeResult|null>(null);const[approveResult,setApproveResult]=useState<ApproveResult|null>(null);const[busy,setBusy]=useState<"intake"|"approve"|null>(null);

 const loadStaging=useCallback(async()=>{if(!supabase){setConnection("Sambungan Supabase tidak tersedia.");return;}setConnection("Memuatkan Semakan Profil...");const{data,error}=await supabase.from("import_staging_company_profiles").select(selectFields).order("created_at",{ascending:false}).limit(500);if(error){setConnection("Jadual Stage Profiling belum tersedia: "+error.message);return;}const rows=((data||[]) as unknown as Array<Record<string,unknown>>).map(mapStage);setStaging(rows);setSelectedStage(c=>c?rows.find(r=>r.id===c.id)||null:null);setConnection("Supabase Connected");},[supabase]);
 useEffect(()=>{void loadStaging();},[loadStaging]);
 const kpis=useMemo(()=>[["Total Preview",preview.length],["Matched",staging.filter(r=>r.match==="Matched").length],["Review Hold",staging.filter(r=>r.status==="Review Hold").length],["Approved",staging.filter(r=>r.status==="Approved").length],["Error",preview.filter(r=>!r.data.company_name.trim()).length]]as const,[preview,staging]);

 async function companies(){if(!supabase)throw new Error("Sambungan Supabase tidak tersedia.");const all:Company[]=[];for(let from=0;;from+=1000){const{data,error}=await supabase.from("companies").select("id,company_name,registration_no").range(from,from+999);if(error)throw error;const page=(data||[])as Company[];all.push(...page);if(page.length<1000)break;}const byReg=new Map<string,Company>(),byName=new Map<string,Company>();for(const c of all){const reg=normReg(c.registration_no),name=normName(c.company_name);if(reg)byReg.set(reg,c);if(name)byName.set(name,c);}return{byReg,byName};}
 function match(row:Preview,index:Awaited<ReturnType<typeof companies>>){const reg=normReg(row.data.registration_no);return(reg?index.byReg.get(reg):undefined)||index.byName.get(normName(row.data.company_name))||null;}

 async function send(rows:Preview[]){if(!supabase){setIntakeMessage("Sambungan Supabase tidak tersedia.");return;}const result:IntakeResult={inserted:0,matched:0,held:0,skipped:0,failed:0};setBusy("intake");setIntakeResult(null);setIntakeMessage("Menghantar ke Semakan Profil...");try{const index=await companies();for(const row of rows){if(!row.data.company_name.trim()){result.skipped++;continue;}try{const{data:old,error:oldError}=await supabase.from("import_staging_company_profiles").select("id").eq("source",row.data.source||file).eq("raw_row_number",row.row).ilike("company_name",row.data.company_name.trim()).limit(1);if(oldError)throw oldError;if((old||[]).length){result.skipped++;continue;}const company=match(row,index),matched=Boolean(company);const{error}=await supabase.from("import_staging_company_profiles").insert({...db(row.data),company_id:company?.id||null,raw_row_number:row.row,match_status:matched?"Matched":"Company Not Found",staging_status:matched?"Ready for Review":"Review Hold",next_action:matched?"Semak dan luluskan ke Profil Syarikat.":"Company belum wujud dalam Induk Syarikat.",review_note:null});if(error)throw error;result.inserted++;if(matched)result.matched++;else result.held++;}catch{result.failed++;}}setIntakeResult({...result});setIntakeMessage(`Staging profil selesai: ${result.inserted} dihantar, ${result.skipped} dilangkau, ${result.failed} gagal.`);await loadStaging();}catch(error){setIntakeMessage("Hantaran gagal: "+(error instanceof Error?error.message:"Ralat tidak diketahui"));}finally{setBusy(null);}}

 async function approveOne(row:Staging){if(!supabase)throw new Error("Sambungan Supabase tidak tersedia.");if(!row.companyId||row.match!=="Matched"||row.status!=="Ready for Review")return"held"as const;const at=new Date().toISOString(),payload={...db(row.data),company_id:row.companyId,raw_row_number:row.row,approved_at:at};const{data:existing,error:checkError}=await supabase.from("company_profiles").select("id").eq("company_id",row.companyId).limit(1).maybeSingle();if(checkError)throw checkError;const outcome:"approved"|"updated"=existing?.id?"updated":"approved";const query=existing?.id?supabase.from("company_profiles").update(payload).eq("company_id",row.companyId):supabase.from("company_profiles").insert(payload);const{error}=await query;if(error)throw error;const{error:stageError}=await supabase.from("import_staging_company_profiles").update({match_status:outcome==="updated"?"Updated Existing Profile":"Imported to Company Profile",staging_status:"Approved",next_action:outcome==="updated"?"Profil syarikat dikemas kini.":"Profil syarikat berjaya diluluskan.",reviewed_at:at,review_note:existing?.id||"New company profile"}).eq("id",row.id);if(stageError)throw stageError;return outcome;}
 async function approveSelected(){if(!selectedStage){setApproveMessage("Pilih baris Semakan Profil dahulu.");return;}setBusy("approve");setApproveMessage("Sedang meluluskan...");try{const result=await approveOne(selectedStage);setApproveMessage(result==="updated"?"Profil syarikat dikemas kini.":result==="approved"?"Profil syarikat diluluskan.":"Baris belum sedia diluluskan.");await loadStaging();}catch(error){setApproveMessage("Kelulusan gagal: "+(error instanceof Error?error.message:"Ralat tidak diketahui"));}finally{setBusy(null);}}
 async function approveAll(){if(!supabase){setApproveMessage("Sambungan Supabase tidak tersedia.");return;}const result:ApproveResult={approved:0,updated:0,held:0,failed:0};setBusy("approve");setApproveResult(null);setApproveMessage("Sedang meluluskan semua baris sedia disemak...");try{const rows:Staging[]=[];for(let from=0;;from+=1000){const{data,error}=await supabase.from("import_staging_company_profiles").select(selectFields).eq("match_status","Matched").eq("staging_status","Ready for Review").order("created_at",{ascending:true}).range(from,from+999);if(error)throw error;const page=((data||[]) as unknown as Array<Record<string,unknown>>).map(mapStage);rows.push(...page);if(page.length<1000)break;}for(const row of rows){try{const outcome=await approveOne(row);if(outcome==="approved")result.approved++;else if(outcome==="updated")result.updated++;else result.held++;}catch{result.failed++;}}setApproveResult({...result});setApproveMessage(`Kelulusan profil selesai: ${result.approved} diluluskan, ${result.updated} dikemas kini, ${result.held} ditahan, ${result.failed} gagal.`);await loadStaging();}catch(error){setApproveMessage("Kelulusan pukal gagal: "+(error instanceof Error?error.message:"Ralat tidak diketahui"));}finally{setBusy(null);}}

 function onCsv(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0];if(!selected){setFile("");setHeaders([]);setMapping(mapHeaders([]));setPreview([]);setSelectedPreview(null);return;}setFile(selected.name);setIntakeMessage("Membaca fail CSV...");const reader=new FileReader();reader.onload=()=>{const parsed=parseCsv(String(reader.result||"")),head=parsed[0]||[],mapped=mapHeaders(head),rows=previewRows(head,parsed.slice(1),mapped,selected.name);setHeaders(head);setMapping(mapped);setPreview(rows);setSelectedPreview(rows[0]||null);setIntakeMessage(rows.length?"Pratonton CSV sedia.":"Tiada baris data dijumpai.");};reader.onerror=()=>setIntakeMessage("Fail CSV tidak dapat dibaca.");reader.readAsText(selected);}
 const ready=staging.filter(r=>r.match==="Matched"&&r.status==="Ready for Review"),selectedReady=selectedStage?.match==="Matched"&&selectedStage?.status==="Ready for Review";

 return <main style={s.page}>
  <header style={s.header}><div><p style={s.eyebrow}>COMPANY MASTER / STAGE PROFILING</p><h1 style={s.title}>Stage Profiling</h1><p style={s.note}>Import Profil Syarikat daripada CSV</p></div><div style={s.actions}><span style={s.badge}>{connection}</span><button type="button" onClick={()=>void loadStaging()} style={s.button}>Muat Semula</button></div></header>
  <div style={s.flow}>CSV Profiling -&gt; Preview -&gt; Hantar ke Semakan Profil -&gt; Semakan Profil -&gt; Luluskan ke Profil Syarikat</div>
  <section style={s.kpis}>{kpis.map(([label,value])=><div key={label} style={s.kpi}><span>{label}</span><strong>{value}</strong></div>)}</section>
  <section style={s.panel}>
   <div style={s.panelHead}><div><h2 style={s.h2}>CSV Upload &amp; Preview</h2><p style={s.note}>Data tidak masuk terus ke Profil Syarikat.</p></div><label style={s.file}>Pilih CSV <input type="file" accept=".csv,text/csv" onChange={onCsv} style={{fontSize:8}}/></label></div>
   {!file?<div style={s.empty}><strong>Tiada fail CSV dipilih.</strong><span>Sila pilih fail CSV Profiling untuk mula pratonton import.</span></div>:<>
    <div style={s.meta}><span><b>Fail:</b> {file}</span><span><b>Header:</b> {headers.length}</span><span><b>Baris:</b> {preview.length}</span></div>
    <details style={s.details}><summary style={s.summary}>Header Dikesan &amp; Column Mapping</summary><div style={s.mapping}>{Object.entries(mapping).map(([field,header])=><div key={field} style={s.mapRow}><span>{field}</span><b>{header||"Tidak dipadankan"}</b></div>)}</div></details>
    <div style={s.tableWrap}><table style={s.table}><thead><tr>{["No","Nama Syarikat","No SSM","Negeri","Email","PIC","Status Profiling","Isu Profiling"].map(x=><th key={x} style={s.th}>{x}</th>)}</tr></thead><tbody>{preview.map(row=><tr key={row.row+row.data.company_name} onClick={()=>setSelectedPreview(row)} style={selectedPreview?.row===row.row?s.active:undefined}><td style={s.td}>{row.row}</td><td style={s.strong}>{row.data.company_name||"Ralat: Nama kosong"}</td><td style={s.td}>{row.data.registration_no||"-"}</td><td style={s.td}>{row.data.state||"-"}</td><td style={s.td}>{row.data.email||"-"}</td><td style={s.td}>{row.data.pic_name||"-"}</td><td style={s.td}>{row.data.profiling_status||"-"}</td><td style={s.td}>{row.data.profiling_issue||"-"}</td></tr>)}</tbody></table></div>
    <div style={s.actions}><button type="button" disabled={!selectedPreview||busy==="intake"} onClick={()=>selectedPreview&&void send([selectedPreview])} style={{...s.primary,opacity:!selectedPreview||busy==="intake"?.45:1}}>Hantar Baris Dipilih ke Semakan Profil</button><button type="button" disabled={!preview.length||busy==="intake"} onClick={()=>void send(preview)} style={{...s.button,opacity:!preview.length||busy==="intake"?.45:1}}>Hantar Semua Baris Sah ke Semakan Profil</button><span style={s.note}>{intakeMessage}</span></div>
    {intakeResult&&<div style={s.result}>{intakeResult.inserted} dihantar, {intakeResult.matched} dipadankan, {intakeResult.held} ditahan, {intakeResult.skipped} dilangkau, {intakeResult.failed} gagal.</div>}
   </>}
  </section>
  <section style={s.panel}>
   <div style={s.panelHead}><div><h2 style={s.h2}>Semakan Profil</h2><p style={s.note}>Semak staging sebelum data diluluskan.</p></div><div style={s.actions}><span style={s.badge}>{ready.length} sedia disemak</span><button type="button" disabled={!ready.length||busy==="approve"||!supabase} onClick={()=>void approveAll()} style={{...s.approve,opacity:!ready.length||busy==="approve"||!supabase?.45:1}}>Luluskan Semua Baris Sedia Disemak</button></div></div>
   <div style={s.review}><div style={s.tableWrap}><table style={s.table}><thead><tr>{["Nama Syarikat","No SSM","Match Status","Staging Status","Next Action"].map(x=><th key={x} style={s.th}>{x}</th>)}</tr></thead><tbody>{staging.length?staging.map(row=><tr key={row.id} onClick={()=>setSelectedStage(row)} style={selectedStage?.id===row.id?s.active:undefined}><td style={s.strong}>{row.data.company_name||"-"}</td><td style={s.td}>{row.data.registration_no||"-"}</td><td style={s.td}><span style={s.badge}>{bm(row.match)}</span></td><td style={s.td}><span style={s.badge}>{bm(row.status)}</span></td><td style={s.td}>{row.next}</td></tr>):<tr><td colSpan={5} style={s.emptyCell}>Belum ada rekod Semakan Profil.</td></tr>}</tbody></table></div>
    <aside style={s.aside}><h3 style={s.h3}>Baris Semakan Dipilih</h3>{!selectedStage?<p style={s.note}>Pilih baris untuk melihat ringkasan dan tindakan.</p>:<>{[["Nama Syarikat",selectedStage.data.company_name],["No SSM",selectedStage.data.registration_no||"-"],["No CIDB",selectedStage.data.cidb_no||"-"],["Negeri",selectedStage.data.state||"-"],["PIC",selectedStage.data.pic_name||"-"],["Match Status",bm(selectedStage.match)],["Staging Status",bm(selectedStage.status)],["Next Action",selectedStage.next]].map(([label,value])=><div key={label} style={s.kv}><span>{label}</span><b>{value}</b></div>)}<button type="button" disabled={!selectedReady||busy==="approve"} onClick={()=>void approveSelected()} style={{...s.approveFull,opacity:!selectedReady||busy==="approve"?.45:1}}>Luluskan Baris Dipilih ke Profil Syarikat</button></>}{approveMessage&&<div style={s.alert}>{approveMessage}</div>}</aside>
   </div>
   {approveResult&&<div style={s.result}>Kelulusan profil selesai: {approveResult.approved} diluluskan, {approveResult.updated} dikemas kini, {approveResult.held} ditahan, {approveResult.failed} gagal.</div>}
  </section>
 </main>;
}

const button={minHeight:28,padding:"5px 8px",border:"1px solid #9ca3af",borderRadius:4,background:"#fff",color:"#111827",fontSize:8,fontWeight:800,cursor:"pointer"};
const td={padding:"5px 6px",borderBottom:"1px solid #e5e7eb",color:"#4b5563",fontSize:8,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap" as const};
const s={
 page:{minHeight:"100vh",padding:14,background:"#f3f4f6",color:"#111827",fontFamily:"Arial, sans-serif",fontSize:10},
 header:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10,marginBottom:8},eyebrow:{margin:"0 0 3px",color:"#6b7280",fontSize:8,fontWeight:800},title:{margin:0,fontSize:20},note:{margin:"3px 0",color:"#6b7280",fontSize:8},
 actions:{display:"flex",alignItems:"center",gap:6,flexWrap:"wrap" as const},badge:{display:"inline-block",maxWidth:360,padding:"3px 5px",border:"1px solid #d1d5db",borderRadius:4,background:"#f9fafb",color:"#4b5563",fontSize:7.5},button,
 flow:{marginBottom:8,padding:"6px 8px",borderLeft:"3px solid #4b5563",background:"#fff",color:"#4b5563",fontSize:8},kpis:{display:"grid",gridTemplateColumns:"repeat(5,minmax(100px,1fr))",gap:6,marginBottom:8},kpi:{display:"flex",justifyContent:"space-between",padding:"7px 8px",border:"1px solid #d1d5db",borderRadius:5,background:"#fff",fontSize:8},
 panel:{minWidth:0,marginBottom:8,padding:9,border:"1px solid #d1d5db",borderRadius:6,background:"#fff"},panelHead:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:7,flexWrap:"wrap" as const},h2:{margin:0,fontSize:11},h3:{margin:"0 0 5px",fontSize:9},
 file:{display:"flex",alignItems:"center",gap:6,padding:"4px 7px",border:"1px solid #9ca3af",borderRadius:4,background:"#f9fafb",fontSize:8,fontWeight:800},empty:{display:"grid",gap:3,padding:14,border:"1px dashed #cbd5e1",background:"#f9fafb",color:"#6b7280",textAlign:"center" as const},meta:{display:"flex",gap:12,marginBottom:6,color:"#4b5563",fontSize:8},
 details:{marginBottom:6,border:"1px solid #e5e7eb",borderRadius:4,background:"#f9fafb"},summary:{padding:"5px 7px",fontSize:8,fontWeight:800,cursor:"pointer"},mapping:{display:"grid",gridTemplateColumns:"repeat(3,minmax(150px,1fr))",gap:4,padding:"0 7px 7px"},mapRow:{display:"flex",justifyContent:"space-between",gap:6,padding:"4px 5px",borderBottom:"1px solid #e5e7eb",fontSize:7.5},
 tableWrap:{minWidth:0,overflowX:"auto" as const},table:{width:"100%",borderCollapse:"collapse" as const,tableLayout:"fixed" as const},th:{padding:"5px 6px",borderBottom:"1px solid #9ca3af",background:"#f3f4f6",color:"#4b5563",fontSize:7.5,textAlign:"left" as const,whiteSpace:"nowrap" as const},td,strong:{...td,color:"#111827",fontWeight:800},active:{background:"#eef6f0",outline:"1px solid #86a98f",cursor:"pointer"},
 primary:{...button,border:"1px solid #111827",background:"#111827",color:"#fff"},approve:{...button,border:"1px solid #166534",background:"#166534",color:"#fff"},approveFull:{...button,width:"100%",marginTop:8,border:"1px solid #166534",background:"#166534",color:"#fff"},result:{marginTop:6,padding:"5px 7px",borderLeft:"3px solid #166534",background:"#f0fdf4",color:"#166534",fontSize:8},
 review:{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(260px,310px)",gap:8,alignItems:"start"},aside:{minWidth:0,padding:7,border:"1px solid #d1d5db",borderRadius:5,background:"#f9fafb"},kv:{display:"grid",gap:2,padding:"5px 1px",borderBottom:"1px solid #e5e7eb",fontSize:8},alert:{marginTop:6,padding:"5px 6px",borderLeft:"3px solid #6b7280",background:"#fff",color:"#4b5563",fontSize:8},emptyCell:{padding:14,color:"#6b7280",fontSize:8,textAlign:"center" as const}
};
