import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

type Row = Record<string, any>;

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""
);

const SYNC_SOURCE = "sync:evidence-index-v3";

function txt(v: any) {
  return String(v ?? "").trim();
}

function n(v: any) {
  return txt(v).toLowerCase();
}

function isUuid(v: any) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(txt(v));
}

function uuidOrNull(v: any) {
  const value = txt(v);
  return isUuid(value) ? value : null;
}

function dateOrNull(v: any) {
  const value = txt(v);
  if (!value) return null;

  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return null;

  return d.toISOString().slice(0, 10);
}

function pick(row: Row | null | undefined, keys: string[], fallback = "") {
  if (!row) return fallback;

  for (const key of keys) {
    const value = row[key];
    if (value !== undefined && value !== null && txt(value) !== "") {
      return txt(value);
    }
  }

  return fallback;
}

function companyName(row: Row) {
  return pick(row, ["company_name", "company", "nama_syarikat", "name", "syarikat"], "Unknown Company");
}

function companyCode(row: Row) {
  return pick(row, ["company_code", "code", "tr_code", "kod_syarikat"], "");
}

function companyId(row: Row) {
  return uuidOrNull(pick(row, ["id", "company_id"]));
}

function sameCompany(evidence: Row, company: Row) {
  const evCode = companyCode(evidence);
  const coCode = companyCode(company);

  if (evCode && coCode && n(evCode) === n(coCode)) return true;

  const evName = companyName(evidence);
  const coName = companyName(company);

  if (evName && coName && n(evName) === n(coName)) return true;

  const evCompanyId = pick(evidence, ["company_id"]);
  const coId = pick(company, ["id", "company_id"]);

  if (evCompanyId && coId && n(evCompanyId) === n(coId)) return true;

  return false;
}

function normalizeStatus(v: any) {
  const value = n(v);

  if (!value) return "available";
  if (value.includes("missing")) return "missing";
  if (value.includes("expired")) return "expired";
  if (value.includes("expiring")) return "expiring";
  if (value.includes("reject")) return "rejected";
  if (value.includes("superseded")) return "superseded";
  if (value.includes("pending")) return "pending";
  if (value.includes("verified")) return "available";
  if (value.includes("available")) return "available";

  return "available";
}

function normalizeVerification(v: any) {
  const value = n(v);

  if (!value) return "pending";
  if (value.includes("verified")) return "verified";
  if (value.includes("mismatch")) return "mismatch";
  if (value.includes("not_applicable")) return "not_applicable";
  if (value.includes("reject")) return "rejected";
  if (value.includes("pending")) return "pending";

  return "pending";
}

function isUsable(row: Row) {
  const status = normalizeStatus(row.status);
  const verification = normalizeVerification(row.verification_status);

  if (status === "missing") return false;
  if (status === "expired") return false;
  if (status === "rejected") return false;
  if (status === "superseded") return false;
  if (verification === "rejected") return false;
  if (verification === "mismatch") return false;

  return true;
}

function buildEvidenceIndexRow(company: Row, evidence: Row, sourceRef: string) {
  return {
    company_id: companyId(company),
    company_code: companyCode(company),
    company_name: companyName(company),
    category_code: pick(evidence, ["category_code", "document_type"], "UNMAPPED"),
    document_title: pick(evidence, ["document_title", "document_name", "title", "document_type", "category_code"], "Evidence Document"),
    document_no: pick(evidence, ["document_no", "certificate_no", "license_no", "serial"]),
    issuing_authority: pick(evidence, ["issuing_authority", "issuer", "authority"]),
    evidence_url: pick(evidence, ["evidence_url", "drive_url", "file_url", "url", "link"]),
    drive_file_id: pick(evidence, ["drive_file_id", "file_id"]),
    issue_date: dateOrNull(pick(evidence, ["issue_date", "tarikh_mula"])),
    expiry_date: dateOrNull(pick(evidence, ["expiry_date", "valid_until", "tarikh_tamat", "end_date"])),
    status: normalizeStatus(pick(evidence, ["status"], "available")),
    verification_status: normalizeVerification(pick(evidence, ["verification_status"], "pending")),
    source_table: SYNC_SOURCE,
    source_ref: sourceRef,
    remarks: "Generated by Evidence Index Sync Engine V3",
  };
}

function buildCompanyInferredEvidence(company: Row) {
  const rows: Row[] = [];

  if (company.ppk_expiry || company.ppk_no || company.ppk) {
    rows.push({
      category_code: "CIDB_PPK",
      document_title: "CIDB PPK Certificate",
      issuing_authority: "CIDB",
      expiry_date: company.ppk_expiry,
      status: "available",
      verification_status: "pending",
    });
  }

  if (company.spkk_expiry || company.spkk_no || company.spkk) {
    rows.push({
      category_code: "CIDB_SPKK",
      document_title: "CIDB SPKK Certificate",
      issuing_authority: "CIDB",
      expiry_date: company.spkk_expiry,
      status: "available",
      verification_status: "pending",
    });
  }

  if (company.stb_expiry || company.stb_no || company.stb) {
    rows.push({
      category_code: "CIDB_STB",
      document_title: "CIDB STB Certificate",
      issuing_authority: "CIDB",
      expiry_date: company.stb_expiry,
      status: "available",
      verification_status: "pending",
    });
  }

  return rows;
}

function buildMissingRow(company: Row, categoryCode: string) {
  return {
    company_id: companyId(company),
    company_code: companyCode(company),
    company_name: companyName(company),
    category_code: categoryCode,
    document_title: `${categoryCode.replaceAll("_", " ")} - Missing`,
    document_no: "",
    issuing_authority: "",
    evidence_url: "",
    drive_file_id: "",
    issue_date: null,
    expiry_date: null,
    status: "missing",
    verification_status: "pending",
    source_table: SYNC_SOURCE,
    source_ref: "mandatory-gap",
    remarks: "Mandatory evidence not detected during sync",
  };
}

function dedupe(rows: Row[]) {
  const map = new Map<string, Row>();

  for (const row of rows) {
    const key = [
      row.company_code,
      row.company_name,
      row.category_code,
      row.document_title,
      row.evidence_url,
      row.expiry_date,
      row.status,
    ].join("|");

    if (!map.has(key)) map.set(key, row);
  }

  return Array.from(map.values());
}

async function readTable(table: string, limit = 50000) {
  const { data, error } = await supabase.from(table).select("*").limit(limit);

  if (error) {
    throw new Error(`${table}: ${error.message}`);
  }

  return data || [];
}

async function insertChunks(table: string, rows: Row[]) {
  const chunkSize = 500;
  let inserted = 0;

  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const { error } = await supabase.from(table).insert(chunk);

    if (error) {
      throw new Error(`Insert ${table} failed at chunk ${i / chunkSize + 1}: ${error.message}`);
    }

    inserted += chunk.length;
  }

  return inserted;
}

export async function POST() {
  try {
    const companies = await readTable("companies", 50000);
    const evidenceRegister = await readTable("evidence_register", 50000);
    const categories = await readTable("evidence_category_master", 5000);

    const mandatoryCodes = categories
      .filter((cat) => cat.is_active !== false)
      .filter((cat) => cat.requirement_level === "mandatory")
      .map((cat) => txt(cat.category_code))
      .filter(Boolean);

    const validCategoryCodes = new Set(
      categories
        .filter((cat) => cat.is_active !== false)
        .map((cat) => txt(cat.category_code))
        .filter(Boolean)
    );

    const allIndexRows: Row[] = [];
    let missingMandatory = 0;
    let sourceMatched = 0;
    let sourceSkippedUnmapped = 0;

    for (const company of companies) {
      const companyRows: Row[] = [];

      const matchedEvidence = evidenceRegister.filter((ev) => sameCompany(ev, company));
      const inferredEvidence = buildCompanyInferredEvidence(company);

      for (const evidence of [...matchedEvidence, ...inferredEvidence]) {
        const categoryCode = pick(evidence, ["category_code", "document_type"]);

        if (!categoryCode) {
          sourceSkippedUnmapped++;
          continue;
        }

        if (!validCategoryCodes.has(categoryCode)) {
          sourceSkippedUnmapped++;
          continue;
        }

        const indexRow = buildEvidenceIndexRow(company, evidence, "evidence_register/company_inference");
        companyRows.push(indexRow);

        if (matchedEvidence.includes(evidence)) {
          sourceMatched++;
        }
      }

      const usableCodes = new Set(
        companyRows
          .filter(isUsable)
          .map((row) => txt(row.category_code))
          .filter(Boolean)
      );

      for (const categoryCode of mandatoryCodes) {
        if (!usableCodes.has(categoryCode)) {
          missingMandatory++;
          companyRows.push(buildMissingRow(company, categoryCode));
        }
      }

      allIndexRows.push(...dedupe(companyRows));
    }

    await supabase
      .from("company_evidence_index")
      .delete()
      .in("source_table", [
        "sync:evidence-index-v1",
        "sync:evidence-index-v2",
        "sync:evidence-index-v3",
      ]);

    const inserted = await insertChunks("company_evidence_index", allIndexRows);

    await supabase.from("sync_run_logs").insert({
      sync_name: "evidence-index-sync-v3",
      status: "success",
      total_companies: companies.length,
      total_source_evidence: evidenceRegister.length,
      total_generated_index: inserted,
      total_missing_mandatory: missingMandatory,
      message: `Matched source evidence: ${sourceMatched}. Skipped unmapped: ${sourceSkippedUnmapped}.`,
    });

    return NextResponse.json({
      ok: true,
      version: "v3",
      companyTable: "companies",
      evidenceTable: "evidence_register",
      categoryTable: "evidence_category_master",
      totalCompanies: companies.length,
      totalSourceEvidence: evidenceRegister.length,
      totalGeneratedIndex: inserted,
      totalMissingMandatory: missingMandatory,
      sourceMatched,
      sourceSkippedUnmapped,
    });
  } catch (error: any) {
    await supabase.from("sync_run_logs").insert({
      sync_name: "evidence-index-sync-v3",
      status: "failed",
      message: error?.message || "Unknown sync error",
    });

    return NextResponse.json(
      {
        ok: false,
        error: error?.message || "Unknown sync error",
      },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    ok: true,
    endpoint: "/api/sync-evidence-index",
    method: "POST",
    version: "v3",
  });
}